const $ = (s) => document.querySelector(s);
const selected = {style:null,motion:false};
const API = (window.GROOVE_API_BASE || '').replace(/\/$/, '');
let trackUrl, trackFile, toastTimer, project;
const notify = (message) => { $('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500); };
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api = async (path, options={}) => { const response=await fetch(`${API}${path}`,options);let data;try{data=await response.json();}catch{data={};}if(!response.ok)throw new Error(data.detail||`Request failed (${response.status})`);return data; };

function updateQueue(){const items=$('#queue-items');items.replaceChildren();for(const [label,isMotion] of [[selected.style,false],[selected.motion?'Motion':null,true]]){if(!label)continue;const button=document.createElement('button');button.className='ingredient'+(isMotion?' motion-chip':'');button.textContent=label;button.title=`Remove ${label}`;button.setAttribute('aria-label',`Remove ${label} from queue`);button.onclick=()=>{if(isMotion)selected.motion=false;else selected.style=null;updateQueue();};items.append(button);}if(!items.children.length){const empty=document.createElement('span');empty.className='empty';empty.textContent='Your world starts here';items.append(empty);}$('#count').textContent=Number(!!selected.style)+Number(selected.motion);document.querySelectorAll('[data-style]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.style===selected.style)));$('#motion').setAttribute('aria-pressed',String(selected.motion));}
document.querySelectorAll('[data-style]').forEach(button=>button.onclick=()=>{selected.style=button.dataset.style;updateQueue();notify(`${selected.style} flowed into your queue`);});
$('#motion').onclick=()=>{selected.motion=!selected.motion;updateQueue();notify(selected.motion?'Motion added to your world':'Motion removed');};
$('#style').onclick=()=>{const hidden=$('#presets').classList.toggle('hidden');$('#style').setAttribute('aria-expanded',String(!hidden));};
$('#see-all').onclick=()=>{$('#search').value='';filterStyles();$('#presets').classList.remove('hidden');$('#style').setAttribute('aria-expanded','true');notify('Explore the four styles inside the lamp');};
function filterStyles(){let visible=0;document.querySelectorAll('.tiles [data-style]').forEach(b=>{b.hidden=!b.dataset.style.toLowerCase().includes($('#search').value.toLowerCase().trim());if(!b.hidden)visible++;});$('#no-results').hidden=visible>0;}
$('#search').addEventListener('input',filterStyles);
$('#upload').onclick=()=>$('#file').click();
$('#file').onchange=()=>{const file=$('#file').files[0];if(!file)return;if(file.type&&!file.type.startsWith('audio/'))return notify('Choose an audio file to start');trackFile=file;if(trackUrl)URL.revokeObjectURL(trackUrl);trackUrl=URL.createObjectURL(file);$('#audio').src=trackUrl;$('#track-name').textContent=file.name.replace(/\.[^.]+$/,'');$('#track-artist').textContent='Your track · ready to analyze';$('#upload-label').textContent='Track ready';project=null;notify('Your song is ready. Choose its world.');};
$('#play').onclick=async()=>{const audio=$('#audio');if(!trackUrl){$('#file').click();return;}if(audio.paused){try{await audio.play();}catch{notify('This audio format could not be played. Try MP3 or WAV.');}}else audio.pause();};
for(const event of ['play','pause','ended'])$('#audio').addEventListener(event,()=>{const playing=!$('#audio').paused;document.body.classList.toggle('playing',playing);$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Pause track':'Play uploaded track');});
$('#audio').ontimeupdate=()=>{const seconds=Math.floor($('#audio').currentTime);$('#time').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;};
$('#audio').onerror=()=>notify('This audio file could not be played. Try MP3 or WAV.');

const panels={Library:['Your private studio','Your current project stays in this private prototype workspace. Persistent accounts and cloud storage are not enabled yet.'],Inspiration:['One song. Endless worlds.','Try Desert for warm landscapes, Dreamlike for lyrical surrealism, Neon for graphic motion, or Cinematic for dramatic film language.'],Community:['Coming later','Community sharing remains disabled while project ownership and persistent storage are being built.'],'Desert Dreams':['Desert Dreams','An example visual direction: a lone traveler, amber dunes, and an enormous moon.']};
function openDialog(title,body){$('#dialog-title').textContent=title;$('#dialog-body').replaceChildren();if(typeof body==='string'){const p=document.createElement('p');p.textContent=body;$('#dialog-body').append(p);}else $('#dialog-body').append(body);$('#dialog').showModal();}
document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>{const key=button.dataset.panel;if(key==='Create'){notify('Choose a track, then give it a world');return;}if(key==='Storyboard'&&project){showStoryboard();return;}openDialog(...(panels[key]||['Storyboard','Analyze a track to build its storyboard.']));});
function setBusy(on,label='Analyzing beats…'){ $('#create').disabled=on;$('#create').innerHTML=on?`${label} <span>◌</span>`:'LET’S MAKE A VIDEO <span>→</span>'; }
$('#create').onclick=async()=>{if(!trackFile){notify('Upload a track first to start your video');$('#file').click();return;}if(!selected.style){notify('Choose a style from the lamp first');$('#presets').classList.remove('hidden');$('#style').setAttribute('aria-expanded','true');return;}const form=new FormData();form.append('audio',trackFile);form.append('style',selected.style);setBusy(true);try{project=await api('/api/groove/projects',{method:'POST',body:form});showStoryboard();}catch(error){notify(error.message);openDialog('The analysis stopped',error.message);}finally{setBusy(false);}};

function storyboardMarkup(){const a=project.analysis,s=project.storyboard;return `<div class="analysis-summary"><strong>${escapeHtml(a.tempo_bpm)} BPM</strong><span>${escapeHtml(a.duration_s)} seconds</span><span>${escapeHtml(a.beat_count)} beats</span><span>${escapeHtml(a.sections.length)} sections</span></div><p class="preview-warning">Storyboard timings are beat-aligned. The animatic uses colored slates—not generated footage—and costs nothing.</p><form id="story-form" class="shot-list">${s.shots.map(shot=>`<article class="shot-row" data-shot="${shot.shot}"><label><input class="approve-shot" type="checkbox"> Approve paid generation</label><strong>${escapeHtml(shot.slate||`Shot ${shot.shot+1}`)}</strong><div class="timing"><input class="shot-start" type="number" step="0.001" min="0" value="${shot.start_s}" aria-label="Shot ${shot.shot+1} start"> → <input class="shot-end" type="number" step="0.001" min="0" value="${shot.end_s}" aria-label="Shot ${shot.shot+1} end"> seconds</div><textarea class="shot-prompt" maxlength="1000" aria-label="Shot ${shot.shot+1} prompt">${escapeHtml(shot.prompt)}</textarea></article>`).join('')}</form><div class="studio-actions"><button id="save-story" type="button">Save storyboard</button><button id="render-animatic" type="button">Render free animatic</button><button id="generate-runway" type="button" class="paid-action">Generate approved shots with Runway</button></div><div id="studio-status" role="status"></div><div id="video-wrap"></div>`;}
function showStoryboard(){const wrap=document.createElement('div');wrap.className='story-studio';wrap.innerHTML=storyboardMarkup();openDialog('Review your storyboard',wrap);$('#save-story').onclick=saveStoryboard;$('#render-animatic').onclick=renderAnimatic;$('#generate-runway').onclick=generateRunway;if(project.animatic_url)showVideo(project.animatic_url,'Colored-slate animatic preview');if(project.final_url)showVideo(project.final_url,'Final generated music video');}
function edits(){return [...document.querySelectorAll('.shot-row')].map(row=>({shot:Number(row.dataset.shot),start_s:Number(row.querySelector('.shot-start').value),end_s:Number(row.querySelector('.shot-end').value),prompt:row.querySelector('.shot-prompt').value.trim()}));}
async function saveStoryboard(){const status=$('#studio-status');status.textContent='Saving storyboard…';try{project=await api(`/api/groove/projects/${project.id}/storyboard`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({shots:edits()})});status.textContent='Storyboard saved.';return true;}catch(error){status.textContent=error.message;return false;}}
async function renderAnimatic(){if(!await saveStoryboard())return;const button=$('#render-animatic');button.disabled=true;$('#studio-status').textContent='Rendering colored-slate animatic with your audio…';try{project=await api(`/api/groove/projects/${project.id}/animatic`,{method:'POST'});$('#studio-status').textContent='Animatic ready. Review every cut before approving generation.';showVideo(project.animatic_url,'Colored-slate animatic preview');}catch(error){$('#studio-status').textContent=error.message;}finally{button.disabled=false;}}
function showVideo(path,label){const wrap=$('#video-wrap');wrap.innerHTML=`<p class="preview-warning"><strong>${escapeHtml(label)}</strong></p><video controls playsinline src="${escapeHtml(API+path)}"></video><a class="download-video" href="${escapeHtml(API+path)}" download>Download MP4</a>`;}
async function generateRunway(){if(!project.animatic_url){$('#studio-status').textContent='Render and review the free animatic before paid generation.';return;}if(!await saveStoryboard())return;const rows=[...document.querySelectorAll('.shot-row')], currentEdits=edits();const shots=rows.map((row,index)=>({shot:Number(row.dataset.shot),approved:row.querySelector('.approve-shot').checked,prompt:currentEdits[index].prompt}));const count=shots.filter(s=>s.approved).length;if(!count){$('#studio-status').textContent='Select at least one shot to approve.';return;}if(!window.confirm(`Submit ${count} approved shot${count===1?'':'s'} to Runway? This can incur provider charges.`))return;const button=$('#generate-runway');button.disabled=true;try{project=await api(`/api/groove/projects/${project.id}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shots})});$('#studio-status').textContent=project.generation.message;pollGeneration();}catch(error){$('#studio-status').textContent=error.message;button.disabled=false;}}
async function pollGeneration(){try{project=await api(`/api/groove/projects/${project.id}`);$('#studio-status').textContent=project.generation?.message||'Waiting for generation…';if(project.generation?.status==='complete'){showVideo(project.final_url,'Final generated music video');$('#generate-runway').disabled=false;return;}if(project.generation?.status==='failed'){$('#generate-runway').disabled=false;return;}setTimeout(pollGeneration,3000);}catch(error){$('#studio-status').textContent=error.message;$('#generate-runway').disabled=false;}}

$('.close').onclick=$('.dialog-done').onclick=()=>$('#dialog').close();
$('#dialog').addEventListener('click',event=>{if(event.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('#dialog').close();}});
for(let i=0;i<23;i++){const b=document.createElement('i');b.className='bubble';const size=3+(i*7%15);Object.assign(b.style,{left:`${8+i*37%85}%`,width:`${size}px`,height:`${size}px`,animationDuration:`${9+i%8}s`,animationDelay:`-${i*1.7}s`});$('#bubbles').append(b);}
for(let i=0;i<60;i++){const bar=document.createElement('i');bar.style.height=`${8+Math.abs(Math.sin(i*.71)*Math.cos(i*.13))*29}px`;bar.style.animationDelay=`-${i*.09}s`;$('#wave').append(bar);}
updateQueue();
